services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  telegram-bot:
    build: ./bot
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEUROCHAIN_API_KEY: ${NEUROCHAIN_API_KEY}
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
    depends_on:
      - postgres
    volumes:
      - ./bot:/app
    restart: always

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./dashboard:/app
    restart: always

volumes:
  postgres_data:
